# Generated by Django 4.1.7 on 2023-02-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='HomeSlider title')),
                ('name', models.CharField(max_length=50, verbose_name='HomeSlider name')),
                ('about', models.TextField(verbose_name='HomeSlider about')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeSlider image')),
                ('logo', models.ImageField(upload_to='media', verbose_name='HomeSlider logo')),
            ],
            options={
                'verbose_name': 'HomeSlider',
                'verbose_name_plural': 'HomeSliders',
            },
        ),
        migrations.CreateModel(
            name='HomeSliderActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='HomeSliderActive title')),
                ('name', models.CharField(max_length=50, verbose_name='HomeSliderActive name')),
                ('about', models.TextField(verbose_name='HomeSliderActive about')),
                ('img', models.ImageField(upload_to='media', verbose_name='HomeSliderActive image')),
                ('logo', models.ImageField(upload_to='media', verbose_name='HomeSliderActive logo')),
            ],
            options={
                'verbose_name': 'HomeSliderActive',
                'verbose_name_plural': 'HomeSlidersActive',
            },
        ),
    ]
